package rules
dialect "java"

import com.baltan.drools.pojo.ItemCity;
import com.baltan.drools.pojo.HelloCity;
import com.baltan.drools.constant.City;
import com.baltan.drools.constant.Type;
import java.math.BigDecimal

rule "Pune Medicine Item"
when
    item : ItemCity(purchaseCity == City.PUNE && typeofItem == Type.MEDICINES)
then
    BigDecimal tax = new BigDecimal(0.0);
    item.setLocalTax(tax.multiply(item.getSellPrice()));
    HelloCity.writeHello(item.getPurchaseCity().toString());
end

rule "Pune Groceries Item"
when
    item : ItemCity(purchaseCity == City.PUNE && typeofItem == Type.GROCERIES)
then
    BigDecimal tax = new BigDecimal(2.0);
    item.setLocalTax(tax.multiply(item.getSellPrice()));
end